package org.entity;
// Generated May 8, 2019 11:07:01 AM by Hibernate Tools 5.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmpDetailsView generated by hbm2java
 */
@Entity
@Table(name="EMP_DETAILS_VIEW"
)
public class EmpDetailsView  implements java.io.Serializable {


     private Long employeeId;
     private String jobId;
     private Long managerId;
     private Long departmentId;
     private Long locationId;
     private String countryId;
     private String firstName;
     private String lastName;
     private Long salary;
     private Long commissionPct;
     private String departmentName;
     private String jobTitle;
     private String city;
     private String stateProvince;
     private String countryName;
     private String regionName;

    public EmpDetailsView() {
    }

	
    public EmpDetailsView(Long employeeId, String jobId, String lastName, String departmentName, String jobTitle, String city) {
        this.employeeId = employeeId;
        this.jobId = jobId;
        this.lastName = lastName;
        this.departmentName = departmentName;
        this.jobTitle = jobTitle;
        this.city = city;
    }
    public EmpDetailsView(Long employeeId, String jobId, Long managerId, Long departmentId, Long locationId, String countryId, String firstName, String lastName, Long salary, Long commissionPct, String departmentName, String jobTitle, String city, String stateProvince, String countryName, String regionName) {
       this.employeeId = employeeId;
       this.jobId = jobId;
       this.managerId = managerId;
       this.departmentId = departmentId;
       this.locationId = locationId;
       this.countryId = countryId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.salary = salary;
       this.commissionPct = commissionPct;
       this.departmentName = departmentName;
       this.jobTitle = jobTitle;
       this.city = city;
       this.stateProvince = stateProvince;
       this.countryName = countryName;
       this.regionName = regionName;
    }
   
     @Id 

    
    @Column(name="EMPLOYEE_ID", nullable=false, precision=6, scale=0)
    public Long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="JOB_ID", nullable=false, length=10)
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    
    @Column(name="MANAGER_ID", precision=6, scale=0)
    public Long getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    
    @Column(name="DEPARTMENT_ID", precision=4, scale=0)
    public Long getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="LOCATION_ID", precision=4, scale=0)
    public Long getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="COUNTRY_ID", length=2)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="FIRST_NAME", length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=25)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="SALARY", precision=8)
    public Long getSalary() {
        return this.salary;
    }
    
    public void setSalary(Long salary) {
        this.salary = salary;
    }

    
    @Column(name="COMMISSION_PCT", precision=2)
    public Long getCommissionPct() {
        return this.commissionPct;
    }
    
    public void setCommissionPct(Long commissionPct) {
        this.commissionPct = commissionPct;
    }

    
    @Column(name="DEPARTMENT_NAME", nullable=false, length=30)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="JOB_TITLE", nullable=false, length=35)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="CITY", nullable=false, length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE_PROVINCE", length=25)
    public String getStateProvince() {
        return this.stateProvince;
    }
    
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }

    
    @Column(name="COUNTRY_NAME", length=40)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="REGION_NAME", length=25)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }




}


