package org.entity;
// Generated May 8, 2019 11:07:01 AM by Hibernate Tools 5.3.6.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name="JOBS"
)
public class Job  implements java.io.Serializable {


     private String jobId;
     private String jobTitle;
     private Long minSalary;
     private Long maxSalary;
     private Set<Employee> employees = new HashSet<Employee>(0);
     private Set<JobHistory> jobHistories = new HashSet<JobHistory>(0);

    public Job() {
    }

	
    public Job(String jobId, String jobTitle) {
        this.jobId = jobId;
        this.jobTitle = jobTitle;
    }
    public Job(String jobId, String jobTitle, Long minSalary, Long maxSalary, Set<Employee> employees, Set<JobHistory> jobHistories) {
       this.jobId = jobId;
       this.jobTitle = jobTitle;
       this.minSalary = minSalary;
       this.maxSalary = maxSalary;
       this.employees = employees;
       this.jobHistories = jobHistories;
    }
   
     @Id 

    
    @Column(name="JOB_ID", unique=true, nullable=false, length=10)
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    
    @Column(name="JOB_TITLE", nullable=false, length=35)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="MIN_SALARY", precision=6, scale=0)
    public Long getMinSalary() {
        return this.minSalary;
    }
    
    public void setMinSalary(Long minSalary) {
        this.minSalary = minSalary;
    }

    
    @Column(name="MAX_SALARY", precision=6, scale=0)
    public Long getMaxSalary() {
        return this.maxSalary;
    }
    
    public void setMaxSalary(Long maxSalary) {
        this.maxSalary = maxSalary;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set<JobHistory> getJobHistories() {
        return this.jobHistories;
    }
    
    public void setJobHistories(Set<JobHistory> jobHistories) {
        this.jobHistories = jobHistories;
    }




}


