package org.entity;
// Generated May 8, 2019 11:07:01 AM by Hibernate Tools 5.3.6.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobHistory generated by hbm2java
 */
@Entity
@Table(name="JOB_HISTORY"
)
public class JobHistory  implements java.io.Serializable {


     private JobHistoryId id;
     private Department department;
     private Employee employee;
     private Job job;
     private Date endDate;

    public JobHistory() {
    }

	
    public JobHistory(JobHistoryId id, Employee employee, Job job, Date endDate) {
        this.id = id;
        this.employee = employee;
        this.job = job;
        this.endDate = endDate;
    }
    public JobHistory(JobHistoryId id, Department department, Employee employee, Job job, Date endDate) {
       this.id = id;
       this.department = department;
       this.employee = employee;
       this.job = job;
       this.endDate = endDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="startDate", column=@Column(name="START_DATE", nullable=false, length=7) ) } )
    public JobHistoryId getId() {
        return this.id;
    }
    
    public void setId(JobHistoryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENT_ID")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOB_ID", nullable=false)
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", nullable=false, length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


