package org.entity;
// Generated May 8, 2019 11:07:01 AM by Hibernate Tools 5.3.6.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="LOCATIONS"
)
public class Location  implements java.io.Serializable {


     private Long locationId;
     private Country country;
     private String streetAddress;
     private String postalCode;
     private String city;
     private String stateProvince;
     private Set<Department> departments = new HashSet<Department>(0);

    public Location() {
    }

	
    public Location(Long locationId, String city) {
        this.locationId = locationId;
        this.city = city;
    }
    public Location(Long locationId, Country country, String streetAddress, String postalCode, String city, String stateProvince, Set<Department> departments) {
       this.locationId = locationId;
       this.country = country;
       this.streetAddress = streetAddress;
       this.postalCode = postalCode;
       this.city = city;
       this.stateProvince = stateProvince;
       this.departments = departments;
    }
   
     @Id 

    
    @Column(name="LOCATION_ID", unique=true, nullable=false, precision=4, scale=0)
    public Long getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COUNTRY_ID")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="STREET_ADDRESS", length=40)
    public String getStreetAddress() {
        return this.streetAddress;
    }
    
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    
    @Column(name="POSTAL_CODE", length=12)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="CITY", nullable=false, length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE_PROVINCE", length=25)
    public String getStateProvince() {
        return this.stateProvince;
    }
    
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


