package org.entity;
// Generated May 8, 2019 11:07:01 AM by Hibernate Tools 5.3.6.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="REGIONS"
)
public class Region  implements java.io.Serializable {


     private Long regionId;
     private String regionName;
     private Set<Country> countries = new HashSet<Country>(0);

    public Region() {
    }

	
    public Region(Long regionId) {
        this.regionId = regionId;
    }
    public Region(Long regionId, String regionName, Set<Country> countries) {
       this.regionId = regionId;
       this.regionName = regionName;
       this.countries = countries;
    }
   
     @Id 

    
    @Column(name="REGION_ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="REGION_NAME", length=25)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<Country> getCountries() {
        return this.countries;
    }
    
    public void setCountries(Set<Country> countries) {
        this.countries = countries;
    }




}


